# Generated by Django 5.1.6 on 2025-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_id_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
